Controllers/MusterilerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcProje.Models.Entity;


namespace MvcProje.Controllers
{
    public class MusterilerController : Controller
    {
        // GET: Musteriler
        MvcDbStokEntities db = new MvcDbStokEntities();

        public ActionResult Index(string p)
        {
            var degerler = from d in db.TBLMUSTERILERs select d;
            if (!string.IsNullOrEmpty(p))
            {
                degerler = degerler.Where(m => m.MUSTERIAD.Contains(p));
            }
            return View(degerler.ToList());

            //var degerler = db.TBLMUSTERILERs.ToList(); 
            //return View(degerler);
        }
        [HttpGet]
        public ActionResult YeniMusteri()
        {
            return View();
        }
        [HttpPost]
        public ActionResult YeniMusteri(TBLMUSTERILER p1)
        {
            if (!ModelState.IsValid)
            {
                return View("YeniMusteri");
            }
            db.TBLMUSTERILERs.Add(p1);
            db.SaveChanges();
            return View();

        }
        public ActionResult SIL(int id)
        {
            var musteri = db.TBLMUSTERILERs.Find(id);
            db.TBLMUSTERILERs.Remove(musteri);
            db.SaveChanges();
            return RedirectToAction("Index");

        }
        public ActionResult MusteriGetir(int id)
        {
            var mus = db.TBLMUSTERILERs.Find(id);
            return View("MusteriGetir", mus);
        }
        public ActionResult Guncelle(TBLMUSTERILER p1)
        {
            var musteri = db.TBLMUSTERILERs.Find(p1.MUSTERIID);
            musteri.MUSTERIAD = p1.MUSTERIAD;
            musteri.MUSTERISOYAD = p1.MUSTERISOYAD;
            db.SaveChanges();
            return RedirectToAction("Index");

        }
    }
}

Views/Musteriler/Index.cshtml
@using MvcProje.Models.Entity
@model List<TBLMUSTERILER>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
@using (Html.BeginForm("Index", "Musteriler", FormMethod.Get))
            {
                <p>
                    <b> Aranacak Müşteri Adı: </b> @Html.TextBox("p")
                    <input  type="submit" value="Ara"/>

                </p>
            }

<table  class="table table-bordered">
  
        <tr>
            <th>MÜŞTERİ ID</th>
            <th>MÜŞTERİ ADI</th>
            <th>MÜŞTERİ SOYADI</th>
            <th>SİL</th>
            <th>GÜNCELLE</th>
            <th>ALERT</th>

        </tr>
  
    <tbody>
        @foreach (var musteri in Model)
        {
            <tr>
                <th>@musteri.MUSTERIID</th>
                <td>@musteri.MUSTERIAD</td>
                <td>@musteri.MUSTERISOYAD</td>
                <td><a href="/MUSTERILER/SIL/@musteri.MUSTERIID" class="btn btn-danger">SİL</a></td>
                <td><a href="/MUSTERILER/MusteriGetir/@musteri.MUSTERIID" class="btn btn-success">GÜNCELLE</a></td>
                <td>
                    @Html.ActionLink("SİL BUTONU", "SIL", new { id=musteri.MUSTERIID }, new { @class = "btn btn-warning", onclick = "return confirm('Silme İşlemini Onaylıyormusunuz')" })
            </td>

        </tr>
    }
    </tbody>

</table>
<a href="/MUSTERILER/YeniMusteri/" class="btn btn-primary">YENİ MÜŞTERİ EKLE</a>

Views/Musteriler/MusteriGetir.cshtml
@model MvcProje.Models.Entity.TBLMUSTERILER
@{
    ViewBag.Title = "MusteriGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using (Html.BeginForm("Guncelle", "Musteriler", FormMethod.Post))
            {
<div class="form-group">
    @Html.LabelFor(m => m.MUSTERIID)
    @Html.TextBoxFor(m => m.MUSTERIID, new { @class = "form-control" })
    <br />
    @Html.LabelFor(m => m.MUSTERIAD)
    @Html.TextBoxFor(m => m.MUSTERIAD, new { @class = "form-control" })

    <br />
    @Html.LabelFor(m => m.MUSTERISOYAD)
    @Html.TextBoxFor(m => m.MUSTERISOYAD, new { @class = "form-control" })

</div>
<div>
    <button class="btn btn-warning">Müşteri Güncelle</button>
</div>

            }

Views/Musteriler/YeniMusteri.cshtml
@model MvcProje.Models.Entity.TBLMUSTERILER

@{
    ViewBag.Title = "YeniMusteri";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<form method="post" class="form-group">
    <div>
        <label>Müşteri Adı</label>
        @Html.TextBoxFor(m => m.MUSTERIAD, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.MUSTERIAD, "", new { @style = "color:red" })

    </div>
    <div>
        <label>Müşteri Soyadı</label>
        @Html.TextBoxFor(m => m.MUSTERISOYAD, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.MUSTERISOYAD, "", new { @style = "color:red" })
    </div>
    <div style="margin-top:15px">
   
        <button class="btn btn-info" id="btn1">Müşteri Ekle</button>
    </div>
    <script>
        $('#btn1').click(function () {
            alert('Müşteri Eklemi İşlemi Yapıldı..!');
        });
    </script>
</form>